WITH CHILD_TABLE AS (
    SELECT
        PARENT_ID,
        COUNT(ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)
SELECT
    ID,
    IFNULL(CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA ED
         LEFT JOIN CHILD_TABLE CT ON ED.ID = CT.PARENT_ID
ORDER BY ID